server:
  port: 8080

spring:
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.106.4.104:3306/wordpress?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  cache:
    jcache:
      config: classpath:ehcache.xml
    type: ehcache
  mvc:
    view:
      suffix: .html
      prefix: /templates/
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  #    prefix: class:/templates/
  resources:
    static-locations: classpath:/templates
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    jedis:
      pool:
        max-idle: 1000
        max-wait:
        min-idle: 1
        max-active: 100
    timeout: 5000s
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.hc.common.pojo
agehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.hc.common.dao: DEBUG
